=== hschoon-dev/secure-iot-gateway/cpc-partition/config/opcua-endpoints.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Restrict IdentifierType -->
    <xs:simpleType name="IdentifierTypeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Numeric"/>
            <xs:enumeration value="String"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Allow Identifier to be int or string -->
    <xs:simpleType name="IdentifierUnion">
        <xs:union memberTypes="xs:int xs:string"/>
    </xs:simpleType>

    <xs:element name="opcua-servers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="server" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="server_app_uri" type="xs:string"/>
                            <xs:element name="client_app_uri" type="xs:string"/>
                            <xs:element name="alias" type="xs:string"/>
                            <xs:element name="security">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="policy" type="xs:string"/>
                                        <xs:element name="mode" type="xs:string"/>
                                        <xs:element name="server_certificate" type="xs:string" minOccurs="0"/>
                                        <xs:element name="client_certificate" type="xs:string" minOccurs="0"/>
                                        <xs:element name="client_private_key" type="xs:string" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="nodes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="node" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="DisplayName" type="xs:string"/>
                                                    <xs:element name="NamespaceIndex" type="xs:int"/>
                                                    <xs:element name="NamespaceAlias" type="xs:string"/>
                                                    <xs:element name="IdentifierType" type="IdentifierTypeEnum"/>
                                                    <xs:element name="Identifier" type="IdentifierUnion"/>
                                                    <xs:element name="datatype" type="xs:string"/>
                                                    <xs:element name="description" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hschoon-dev/secure-iot-gateway/cpc-partition/config/opcua-endpoints_identifier-type-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<opcua-servers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="opcua-endpoints.xsd">

 <server>
    <server_app_uri>opc.tcp://172.16.4.52:4840</server_app_uri>
    <client_app_uri>urn:S7-1500-Siemens</client_app_uri>
    <alias>s7-1500-siemens-sps</alias>
    <security>
      <policy>SecurityPolicyNone</policy>
      <mode>None</mode>
    </security>
    <nodes>
  
      <node>
        <DisplayName>Produzierte_Takte</DisplayName>
        <NamespaceIndex>3</NamespaceIndex>
        <NamespaceAlias>S7-1500</NamespaceAlias>
        <IdentifierType>String</IdentifierType>
        <Identifier>"ProductionData"."Produzierte_Takte"</Identifier>
        <datatype>Int32</datatype>
        <description>Haifischfuetterung</description>
      </node>
      
    </nodes>
  </server>

  
</opcua-servers>
